api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views

router_v1 = DefaultRouter()
router_v1.register('ingredients', views.IngredientListView,
                   basename='ingredients')

urlpatterns = [
    path('', include(router_v1.urls)),
    path('favorites/', views.FavoriteView.as_view()),
    path('favorites/<int:pk>/', views.FavoriteView.as_view()),
    path('purchases/', views.ShoppingListView.as_view()),
    path('purchases/<int:pk>/', views.ShoppingListView.as_view()),
    path('subscriptions/', views.SubscriptionView.as_view()),
    path('subscriptions/<int:pk>/', views.SubscriptionView.as_view())

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import path, include

handler404 = "recipes.views.page_not_found"  # noqa
handler500 = "recipes.views.server_error"  # noqa

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('user/', include('users.urls', namespace='users')),
    path('about-us/', views.flatpage, {'url': '/about-us/'},
         name='about'),
    path('tech/', views.flatpage, {'url': '/tech/'},
         name='tech'),
    path('', include('recipes.urls', namespace='recipes')),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('subscriptions/', views.SubscriptionsList.as_view(),
         name='subscriptions'),
    path('favorites/', views.FavoritesList.as_view(),
         name='favorites'),

    path('shopping_list/', views.ShopList.as_view(), name='shopping_list'),
    path('shopping_list/download/', views.shop_list_export_to_pdf,
         name='shopping_list_download'),
    path('shopping_list/<int:pk>/delete/', views.delete_recipe_from_list,
         name='shopping_list_delete'),

    path('create-recipe/', views.RecipeCreate.as_view(), name='create-recipe'),
    path('create-recipe/<int:pk>', views.RecipeUpdate.as_view(),
         name='update-recipe'),
    path('<int:pk>/', views.RecipeDetail.as_view(), name='recipe_detail'),
    path('<int:pk>/delete/', views.RecipeDelete.as_view(),
         name='recipe_delete'),
    path('<str:username>/', views.UserRecipes.as_view(), name='user_recipes'),
    path('', views.RecipeList.as_view(), name='recipes'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),


]

templates/includes/favorite_button.html
{% if recipe.is_favorite or favorite_page %}
    <button class="button button_style_none"
            name="favorites">
        <span class="icon-favorite icon-favorite_active"></span>
    </button>
{% else %}
    <button class="button button_style_none"
            name="favorites"
            data-out><span
            class="icon-favorite"></span>
    </button>
{% endif %}

templates/includes/footer.html
{% load flatpages %}
{% get_flatpages as flatpages %}

<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'recipes:recipes' %}" class="footer__brand link">Продуктовый
            помощник</a>
        <ul class="footer__items">
            {% for page in flatpages %}
                <li class="footer__item">
                    <a href="{{ page.url }}"
                       class="footer__link link">{{ page.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</footer>

templates/includes/navbar.html
<nav class="nav">
    <div class="nav__container container">
        {% if user.is_authenticated %}
            <ul class="nav__items list">
                {% url "recipes:recipes" as index_url %}
                <li class="nav__item {% if index_url == request.path %}
                nav__item_active{% endif %}">
                    <a href="{{ index_url }}"
                       class="nav__link link">Рецепты</a>
                </li>
                {% url "recipes:subscriptions" as subscriptions_url %}
                <li class="nav__item {% if subscriptions_url == request.path %}
                nav__item_active{% endif %}">
                    <a href="{{ subscriptions_url }}"
                       class="nav__link link">Мои подписки
                    </a>
                </li>
                {% url "recipes:create-recipe" as create_recipe_url %}
                <li class="nav__item {% if create_recipe_url == request.path %}
                nav__item_active{% endif %}">
                    <a href="{{ create_recipe_url }}"
                       class="nav__link link">Создать рецепт
                    </a>
                </li>
                {% url "recipes:favorites" as favorites_url %}
                <li class="nav__item {% if favorites_url == request.path %}
                nav__item_active{% endif %}">
                    <a href="{{ favorites_url }}"
                       class="nav__link link">
                        Избранное
                    </a>
                </li>
                {% url "recipes:shopping_list" as shopping_list_url %}
                <li class="nav__item {% if shopping_list_url == request.path %}
                nav__item_active{% endif %}">
                    <a href="{{ shopping_list_url }}"
                       class="nav__link link">Список покупок</a>
                    <span class="badge badge_style_blue nav__badge"
                          id="counter">{{ recipes_in_list }}</span></li>

            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="{% url 'password_change' %}"
                                         class="nav__link link">Изменить
                    пароль</a></li>
                <li class="nav__item"><a href="{% url 'logout' %}"
                                         class="nav__link link">Выход</a></li>
            </ul>
        {% else %}
            <ul class="nav__items list">
                {% url "recipes:recipes" as index_url %}
                <li class="nav__item {% if index_url == request.path %}
                nav__item_active{% endif %}">
                    <a href="{{ index_url }}"
                       class="nav__link link">Рецепты
                    </a>
                </li>
                {% url "recipes:shopping_list" as shopping_list_url %}
                <li class="nav__item {% if shopping_list_url == request.path %}
                nav__item_active{% endif %}">
                    <a href="{{ shopping_list_url }}"
                       class="nav__link link">Список покупок
                        <span class="badge badge_style_blue nav__badge"
                              id="counter">{{ recipes_in_list }}</span>
                    </a>
                </li>
            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="{% url 'login' %}"
                                         class="nav__link link">Войти</a></li>
                <li class="nav__item"><a href="{% url 'users:register' %}"
                                         class="button button_style_blue">Создать
                    аккаунт</a></li>
            </ul>
        {% endif %}
    </div>
</nav>

templates/includes/pagination.html
{% load user_filters %}
{% if is_paginated %}
    <nav class="pagination" aria-label="Search results pages">
        <ul class="pagination__container">

            {% if page_obj.has_previous %}
                <li class="pagination__item">
                    <a class="pagination__link link"
                       href="?{% add_tags_to_pagination request 'page' i %}">
                        <span class="icon-left"></span>
                    </a>
                </li>
            {% endif %}

            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="pagination__item pagination__item_active">
                        <a class="pagination__link link"
                           href="?{% add_tags_to_pagination request 'page' i %}">{{ i }}</a>
                    </li>
                {% elif i >= page_obj.number|add:-4 and i <= page_obj.number|add:4 %}
                    <li class="pagination__item">
                        <a class="pagination__link link"
                           href="?{% add_tags_to_pagination request 'page' i %}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="pagination__item">
                    <a class="pagination__link link"
                       href="?{% add_tags_to_pagination request 'page' i %}">
                        <span class="icon-right"></span>
                    </a>
                </li>
            {% endif %}

        </ul>
    </nav>
{% endif %}

templates/includes/subscribe_button.html
{% load user_filters %}

{% if user != recipe.author %}
    {% if recipe.author|is_follow:user %}
        <li class="single-card__item">
            <button class="button button_style_light-blue button_size_auto"
                    name="subscribe">
                Отписаться от автора
            </button>
        </li>
    {% else %}
        <li class="single-card__item">
            <button class="button button_style_light-blue button_size_subscribe"
                    name="subscribe" data-out>
                Подписаться на автора
            </button>
        </li>
    {% endif %}
{% endif %}

templates/includes/subscribe_button_for_author_page.html
{% load user_filters %}

{% if user.is_authenticated %}
    {% if user != author %}
        <div class="author-subscribe"
             data-author="{{ author.id }}">
            <p style="padding: 0 0 2em 0;">
                {% if author|is_follow:user %}

                    <button class="button button_style_light-blue button_size_auto"
                            name="subscribe">
                        Отписаться от автора
                    </button>

                {% else %}
                    <button class="button button_style_light-blue button_size_subscribe"
                            name="subscribe" data-out>
                        Подписаться на автора
                    </button>

                {% endif %}
            </p>
        </div>
    {% endif %}
{% endif %}