api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views

router_v1 = DefaultRouter()
router_v1.register('ingredients', views.IngredientListView,
                   basename='ingredients')

urlpatterns = [
    path('', include(router_v1.urls)),
    path('favorites/', views.FavoriteView.as_view()),
    path('favorites/<int:pk>/', views.FavoriteView.as_view()),
    path('purchases/', views.ShoppingListView.as_view()),
    path('purchases/<int:pk>/', views.ShoppingListView.as_view()),
    path('subscriptions/', views.SubscriptionView.as_view()),
    path('subscriptions/<int:pk>/', views.SubscriptionView.as_view())

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import path, include

handler404 = "recipes.views.page_not_found"  # noqa
handler500 = "recipes.views.server_error"  # noqa

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('user/', include('users.urls', namespace='users')),
    path('about-us/', views.flatpage, {'url': '/about-us/'},
         name='about'),
    path('tech/', views.flatpage, {'url': '/tech/'},
         name='tech'),
    path('', include('recipes.urls', namespace='recipes')),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('subscriptions/', views.SubscriptionsList.as_view(),
         name='subscriptions'),
    path('favorites/', views.FavoritesList.as_view(),
         name='favorites'),

    path('shopping_list/', views.ShopList.as_view(), name='shopping_list'),
    path('shopping_list/download/', views.shop_list_export_to_pdf,
         name='shopping_list_download'),
    path('shopping_list/<int:pk>/delete/', views.delete_recipe_from_list,
         name='shopping_list_delete'),

    path('create-recipe/', views.RecipeCreate.as_view(), name='create-recipe'),
    path('create-recipe/<int:pk>', views.RecipeUpdate.as_view(),
         name='update-recipe'),
    path('<int:pk>/', views.RecipeDetail.as_view(), name='recipe_detail'),
    path('<int:pk>/delete/', views.RecipeDelete.as_view(),
         name='recipe_delete'),
    path('<str:username>/', views.UserRecipes.as_view(), name='user_recipes'),
    path('', views.RecipeList.as_view(), name='recipes'),
]

recipes/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator as MinValue
from django.db import models
from django.urls import reverse

User = get_user_model()


class Tag(models.Model):
    name = models.CharField('Название тега', max_length=100, unique=True)
    slug = models.SlugField('Слаг', max_length=100, unique=True)
    style = models.CharField('Текст CSS стиля', max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.name


class RecipeManager(models.Manager):

    def all_with_tags_and_authors(self):
        qs = self.get_queryset()
        return qs.select_related('author').prefetch_related('tag')


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='recipes', verbose_name='Автор', )
    name = models.CharField('Название', max_length=255)
    image = models.ImageField('Изображение', upload_to='recipes/%Y/%m/%d/', )
    description = models.TextField('Описание', )
    ingredients = models.ManyToManyField('Ingredient',
                                         through='IngredientForRecipe', )
    tag = models.ManyToManyField(Tag, verbose_name='Тег')
    cook_time = models.PositiveIntegerField(
        validators=[MinValue(1, 'Время приготвления не может быть  0'), ],
        verbose_name='Время приготовления')
    created = models.DateTimeField('Дата добавления', auto_now_add=True)

    objects = RecipeManager()

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ('-created',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('recipes:recipe_detail', kwargs={'pk': self.pk})


class Ingredient(models.Model):
    title = models.CharField('Название', max_length=255, unique=True)
    dimension = models.CharField('Еденица измерения', max_length=20,
                                 default='шт.')
    draft = models.BooleanField('Черновик', default=True)

    class Meta:
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'
        ordering = ('title',)

    def __str__(self):
        return self.title


class IngredientForRecipe(models.Model):
    recipe = models.ForeignKey(Recipe, verbose_name='Рецепт',
                               on_delete=models.CASCADE,
                               related_name='get_ingredients')
    ingredient = models.ForeignKey(Ingredient, verbose_name='Ингредиент',
                                   on_delete=models.CASCADE, )
    count = models.PositiveIntegerField(
        validators=[MinValue(1, 'Время приготвления не может быть  0'), ],
        verbose_name='Количество')

    class Meta:
        verbose_name = 'Ингредиент для рецетов'
        verbose_name_plural = 'Ингредиенты для рецетов'
        constraints = [
            models.UniqueConstraint(fields=['ingredient', 'recipe'],
                                    name='unique_ingredient'),
        ]

    def __str__(self):
        return f"{self.recipe.name} {self.ingredient.title}"


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             verbose_name='Пользователь',
                             )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,
                               verbose_name='Рецепт')

    class Meta:
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранные'
        constraints = [
            models.UniqueConstraint(fields=['user', 'recipe'],
                                    name='unique_favorites'),
        ]

    def __str__(self):
        return f"{self.user} | {self.recipe}"


class ShoppingList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             verbose_name='Пользователь')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,
                               verbose_name='Рецепт')

    class Meta:
        verbose_name = 'Список покупок'
        verbose_name_plural = 'Списки покупок'
        constraints = [
            models.UniqueConstraint(fields=['user', 'recipe'],
                                    name='unique_recipe'),
        ]

    def __str__(self):
        return f"{self.user} | {self.recipe}"

recipes/forms.py
from django import forms
from django.contrib.auth import get_user_model

from recipes.models import Recipe

User = get_user_model()


class RecipeForm(forms.ModelForm):
    author = forms.ModelChoiceField(
        queryset=User.objects.all(),
        disabled=True,
        widget=forms.HiddenInput
    )

    class Meta:
        model = Recipe
        fields = ['name', 'tag', 'cook_time', 'description', 'image',
                  'author']
        widgets = {
            'tag': forms.CheckboxSelectMultiple(),
        }

recipes/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, reverse, render
from django.urls import reverse_lazy
from django.views import generic

from config.settings import PAGINATE_COUNT
from recipes.forms import RecipeForm
from recipes.models import Recipe, Tag, ShoppingList
from .mixins import IsAuthorMixin, FormValidRecipeMixin
from .shop_list import ShopListSession
from .utils import filter_qs_by_tags, is_favorite_and_in_shopping_list, \
    get_data_for_shop_list

User = get_user_model()


class RecipeList(generic.ListView):
    queryset = Recipe.objects.all_with_tags_and_authors()
    template_name = 'recipes/index.html'
    context_object_name = 'recipes'
    paginate_by = PAGINATE_COUNT

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        if not self.request.user.is_authenticated:
            session = ShopListSession(self.request)
            context['shop_list'] = session.sl.values()
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.is_authenticated:
            qs = is_favorite_and_in_shopping_list(qs, self.request.user)

        return filter_qs_by_tags(self.request, qs)


class RecipeDetail(generic.DetailView):
    model = Recipe
    template_name = 'recipes/recipe_detail.html'
    context_object_name = 'recipe'
    queryset = Recipe.objects.select_related('author'). \
        prefetch_related('get_ingredients__ingredient')

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.is_authenticated:
            qs = is_favorite_and_in_shopping_list(qs, self.request.user)
        return qs


class RecipeCreate(LoginRequiredMixin, FormValidRecipeMixin,
                   generic.CreateView):
    form_class = RecipeForm
    template_name = 'recipes/create_edit_recipe.html'

    def get_initial(self):
        return {'author': self.request.user.id}


class RecipeUpdate(LoginRequiredMixin, IsAuthorMixin,
                   FormValidRecipeMixin, generic.UpdateView):
    form_class = RecipeForm
    queryset = Recipe.objects.prefetch_related('get_ingredients__ingredient')
    template_name = 'recipes/create_edit_recipe.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['edit'] = True
        return context


class RecipeDelete(LoginRequiredMixin, IsAuthorMixin, generic.DeleteView):
    model = Recipe
    template_name = 'recipes/recipe_delete.html'
    context_object_name = 'recipe'
    success_url = reverse_lazy('recipes:recipes')


class UserRecipes(RecipeList):
    template_name = 'recipes/user_recipes.html'

    def get(self, request, *args, **kwargs):
        username = self.kwargs.get('username')
        self.user = get_object_or_404(User, username=username)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        qs = self.user.recipes.all_with_tags_and_authors()
        if self.request.user.is_authenticated:
            qs = is_favorite_and_in_shopping_list(qs, self.request.user)
        return filter_qs_by_tags(self.request, qs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = self.user
        context['author_page'] = True
        return context


class SubscriptionsList(LoginRequiredMixin, generic.ListView):
    context_object_name = 'subscriptions'
    template_name = 'recipes/subscriptions.html'
    paginate_by = PAGINATE_COUNT

    def get_queryset(self):
        user = self.request.user
        return user.follower.all().select_related('author')


class FavoritesList(LoginRequiredMixin, RecipeList):
    template_name = 'recipes/favorites.html'

    def get_queryset(self):
        qs = Recipe.objects.all_with_tags_and_authors().filter(
            favorite__user=self.request.user)
        return filter_qs_by_tags(self.request, qs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['favorite_page'] = True
        print(self.request.session.items())
        return context


class ShopList(generic.ListView):
    template_name = 'recipes/shopping_list.html'
    context_object_name = 'recipes'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            qs = Recipe.objects.filter(shoppinglist__user=self.request.user)
        else:
            session = ShopListSession(self.request)
            recipe_ids = session.sl.keys()
            qs = Recipe.objects.filter(id__in=recipe_ids)
        return qs


def delete_recipe_from_list(request, pk):
    if request.user.is_authenticated:
        ShoppingList.objects.filter(user=request.user,
                                    recipe_id=pk).delete()
    else:
        session = ShopListSession(request)
        session.remove(str(pk))
    return redirect(reverse('recipes:shopping_list'))


def shop_list_export_to_pdf(request):
    if request.user.is_authenticated:
        recipes = Recipe.objects.filter(shoppinglist__user=request.user)
    else:
        session = ShopListSession(request)
        recipe_ids = session.sl.keys()
        recipes = Recipe.objects.filter(id__in=recipe_ids)

    data = get_data_for_shop_list(recipes)

    response = HttpResponse(data,
                            content_type='application/text charset=utf-8')
    response['Content-Disposition'] = 'attachment; filename="ShoppingList.txt"'
    return response


def page_not_found(request, exception):
    return render(request, "misc/404.html", {"path": request.path}, status=404)


def server_error(request):
    return render(request, "misc/500.html", status=500)

templates/recipes/create_edit_recipe.html
{% extends 'base.html' %}
{% load user_filters %}
{% load static %}
{% block title %}
    {% if edit %}
        Редактирование
    {% else %}
        Создание
    {% endif %}
    рецепта
{% endblock %}


{% block content %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">
                {% if edit %}
                    Редактирование
                {% else %}
                    Создание
                {% endif %}
                рецепта</h1>
        </div>
        <div class="form-container">
            <form class="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form__group">
                    <label for="id_name"
                           class="form__label">{{ form.name.label }}</label>
                    <div class="form__field-group">
                        {{ form.name|add_class:"form__input" }}
                        <span class="form__error"></span>
                    </div>
                </div>
                <div class="form__group">
                    <p class="form__label">Теги</p>
                    <div class="form__field-group">
                        <div class="tags">

                            {% for tag in form.tag %}
                                <div class="tags__item">
                                    <label class="tags__label">{{ tag|tag_format_class }}</label>
                                </div>
                            {% endfor %}
                        </div>
                        <span class="form__error">{{ form.tag.errors }}</span>

                    </div>
                </div>
                <div class="form__group">
                    <label for="nameIngredient"
                           class="form__label">Ингредиенты</label>
                    <div class="form__field-group">
                        <div class="form__field-group-ingredientes">
                            <div class="form__dropdown">
                                <input type="text" id="nameIngredient"
                                       class="form__input">
                                <div class="form__dropdown-items"></div>
                                <div class="form__dropdown-items"></div>
                            </div>
                            <input type="number" id="cantidad"
                                   class="form__input" min="0">
                            <label for="cantidad" class="form__label"
                                   id="cantidadVal">шт.</label>
                        </div>
                        <div class="form__field-group-ingredientes-container">
                            {% if edit %}
                                {% for ingredient in form.instance.get_ingredients.all %}
                                    {% with forloop.counter as counter %}
                                        <div class="form__field-item-ingredient"
                                             id="ing_{{ counter }}">
                                        <span> {{ ingredient.ingredient.title }}
                                            {{ ingredient.count }}{{ ingredient.ingredient.dimension }}</span>
                                            <span class="form__field-item-delete"></span>
                                            <input id="nameIngredient_{{ counter }}"
                                                   name="nameIngredient_{{ counter }}"
                                                   type="hidden"
                                                   value="{{ ingredient.ingredient.title }}">
                                            <input id="valueIngredient_{{ counter }}"
                                                   name="valueIngredient_{{ counter }}"
                                                   type="hidden"
                                                   value="{{ ingredient.count }}">
                                            <input id="unitsIngredient_{{ counter }}"
                                                   name="unitsIngredient_{{ counter }}"
                                                   type="hidden"
                                                   value="{{ ingredient.ingredient.dimension }}">
                                        </div>
                                    {% endwith %}
                                {% endfor %}
                            {% endif %}
                        </div>
                        <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                        <span class="form__error">{{ form.non_field_errors }}</span>
                    </div>
                </div>
                <div class="form__group">
                    <label for="id_time" class="form__label">Время
                        приготовления</label>
                    <div class="form__field-group form__field-group_time">
                        {{ form.cook_time|add_class:"form__input" }}
                        <label for="id_time" class="form__label">минут</label>
                        <span class="form__error">{{ form.cook_time.errors }}</span>
                    </div>
                </div>
                <div class="form__group">
                    <label for="id_description"
                           class="form__label">Описание</label>
                    <div class="form__field-group">
                        {{ form.description|add_class:"form__textarea" }}
                        <span class="form__error">{{ form.description.errors }}</span>
                    </div>
                </div>
                <div class="form__group">
                    <span class="form__label">Загрузить фото</span>
                    <div class="form__field-group">
                        {{ form.image }}
                        <span class="form__error">{{ form.image.errors }}</span>
                    </div>
                </div>
                <div class="form__footer">
                    <button class="button button_style_blue">
                        Сохранить
                    </button>
                    {% if edit %}
                        <a style="margin-left: 2.5em"
                           href="{% url 'recipes:recipe_delete' recipe.id %}"
                           class="form__ingredient-link">Удалить</a>
                    {% endif %}
                </div>
            </form>
        </div>
    </main>
{% endblock %}

{% block js %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/formRecipe.js' %}"></script>
{% endblock %}

templates/recipes/favorites.html
{% extends 'recipes/index.html' %}
{% block title %}
    Избранное
{% endblock %}
{% block header %}
    Избранное
{% endblock %}

templates/recipes/recipe.html
{% load user_filters %}
<div class="card" data-id="{{ recipe.id }}">
    <a href="{{ recipe.get_absolute_url }}" class="link" target="_blank"><img
            src="{{ recipe.image.url }}" alt="Какой-то текст"
            class="card__image"></a>
    <div class="card__body">
        <a class="card__title link" href="{{ recipe.get_absolute_url }}"
           target="_blank">{{ recipe.name }}</a>
        <ul class="card__items">
            {% for tag in recipe.tag.all %}
                <li class="card__item">
                    <span class="badge badge_style_{{ tag.style }}">
                        {{ tag.name }}
                    </span>
                </li>
            {% endfor %}
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span
                    class="icon-time"></span> {{ recipe.cook_time }}
                мин.</p>
            <p class="card__text"><span class="icon-user"></span>
                <a href="{% url 'recipes:user_recipes' recipe.author %}"
                   style="color: black">{{ recipe.author.username }}</a>
            </p>
        </div>
    </div>

    <div class="card__footer">
        {% if recipe.in_list or recipe.id in shop_list %}
            <button class="button button_style_light-blue-outline"
                    name="purchases"><span
                    class="icon-check button__icon"></span>
                Рецепт добавлен
            </button>
        {% else %}
            <button class="button button_style_light-blue"
                    name="purchases" data-out><span
                    class="icon-plus button__icon"></span>
                Добавить в покупки
            </button>

        {% endif %}
        {% if user.is_authenticated %}
            {% include 'includes/favorite_button.html' %}
        {% endif %}
    </div>
</div>

templates/recipes/recipe_delete.html
{% extends "base.html" %}
{% block title %}Удаление рецепта{% endblock %}

{% block content %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Удаление рецепта "{{ recipe.name }}"</h1>
        </div>
        <div class="form-container">
            <form class="form" method="post">
                {% csrf_token %}
                <p class="form__info-text">
                    Вы уверены, что хотите удалить рецепт ?
                </p>
                <div class="form__footer">
                    <button class="button button_style_blue">Удалить</button>
                    <a style="margin-left: 2.5em"
                       href="{% url 'recipes:update-recipe' recipe.id %}"
                       class="form__ingredient-link">Назад</a>
                </div>
            </form>
        </div>
    </main>

{% endblock %}

templates/recipes/recipe_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% load static %}
{% block title %}
    {{ recipe.name }}
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'pages/single.css' %}">
{% endblock %}

{% block content %}
    {% csrf_token %}
    <main class="main container">
        <div class="single-card" data-id="{{ recipe.id }}"
             data-author="{{ recipe.author.id }}">
            <img src="{{ recipe.image.url }}" alt="какой-то текст"
                 class="single-card__image">
            <div class="single-card__info">
                <div class="single-card__header-info">
                    <h1 class="single-card__title">{{ recipe.name }}</h1>
                    <div class="single-card__favorite">
                        {% include 'includes/favorite_button.html' %}
                        <div class="single-card__favorite-tooltip tooltip">
                            Добавить в избранное
                        </div>
                    </div>
                </div>
                <ul class="single-card__items">
                    {% for tag in recipe.tag.all %}
                        <li class="card__item">
                            <span class="badge badge_style_{{ tag.style }}">
                                {{ tag.name }}
                            </span>
                        </li>
                    {% endfor %}

                </ul>
                <div class="single-card__items single-card__items_column">
                    <p class="single-card__text"><span
                            class="icon-time"></span> {{ recipe.cook_time }}
                        мин.
                    </p>
                    <ul class="single-card__items">
                        <li class="single-card__item"><p
                                class="single-card__text">
                            <span class="icon-user"></span>
                            <a href="{% url 'recipes:user_recipes' recipe.author %}"
                               style="color: black">{{ recipe.author }}
                            </a>
                        </p>
                        </li>
                        {% if user == recipe.author %}
                            <li class="single-card__item"><a
                                    style="margin-left: 2.5em"
                                    href="{% url 'recipes:update-recipe' recipe.id %}"
                                    class="single-card__text">Редактировать
                                рецепт</a></li>
                        {% endif %}
                    </ul>
                </div>
                {% if user.is_authenticated %}
                    <ul class="single-card__items">
                        <li class="single-card__item">
                            {% if recipe.in_list %}
                                <button class="button button_style_light-blue-outline"
                                        name="purchases"><span
                                        class="icon-check button__icon"></span>
                                    Рецепт добавлен
                                </button>
                            {% else %}
                                <button class="button button_style_blue"
                                        name="purchases"
                                        data-out><span
                                        class="icon-plus"></span>
                                    Добавить в покупки
                                </button>
                            {% endif %}
                        </li>

                        {% include 'includes/subscribe_button.html' %}
                    </ul>
                {% endif %}
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Ингридиенты:</h3>
                    <div class="single-card__items single-card__items_column">
                        {% for ingredient in recipe.get_ingredients.all %}
                            <p class=" single-card__section-item">{{ ingredient.ingredient.title }}
                                - {{ ingredient.count }} {{ ingredient.ingredient.dimension }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Описание:</h3>
                    <p class=" single-card__section-text">{{ recipe.description|linebreaksbr }}</p>
                </div>
            </div>
        </div>
    </main>
{% endblock %}



{% block js %}
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/config/config.js' %}"></script>

    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/SingleCard.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/singlePage.js' %}"></script>
{% endblock %}

templates/recipes/shopping_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Список покупок{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'pages/shopList.css' %}">
{% endblock %}

{% block content %}

    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Список покупок</h1>
        </div>
        <div class="card-list card-list_column">
            <ul class="shopping-list">
                {% for recipe in recipes %}

                    <li class="shopping-list__item" data-id="{{ recipe.id }}">
                        <div class="recipe recipe_reverse">
                            <img src="{{ recipe.image.url }}"
                                 alt="какой-то текст"
                                 class="recipe__image recipe__image_big">

                            <a href="{{ recipe.get_absolute_url }}"><h3
                                    class="recipe__title">{{ recipe.name }}</h3>
                            </a>
                            <p class="recipe__text"><span
                                    class="icon-time"></span>
                                {{ recipe.cook_time }} мин.</p>
                        </div>
                        <a href="{% url 'recipes:shopping_list_delete' recipe.id %}"
                           class="shopping-list__button link">Удалить</a>
                    </li>
                {% empty %}
                    <h3 class="main__title">
                        Вы не добавили ни одного рецепта в список покупок
                    </h3>
                {% endfor %}
            </ul>
            {% if recipes %}
                <a href="{% url 'recipes:shopping_list_download' %}">
                    <button class="button button_style_blue">Скачать список
                    </button>
                </a>
            {% endif %}
        </div>
    </main>
{% endblock %}

{% block js %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/components/ShopList.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/shopList.js' %}"></script>
{% endblock %}